# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI-Conversão Temperatura

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Possibilita a execução manual via aba Actions
  workflow_dispatch:

jobs:
  # Job name
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DevOps/01_Conversao-Temperatura
        
    # Sequência de Tarefas que serão executadas no job
    steps:
    - uses: actions/checkout@v4

    # Configurando Ambiente Node -> Versão tem que ser igual ao app
    - name: Setup do Node.js
      uses: actions/setup-node@v4.1.0
      with: 
        node-version: 20.10.0
        
    # Configuração do Ambiente de Teste
    - name: Instalação do Mocha e dos Pacotes de Teste
      run: |
        cd src;
        npm install -g mocha;
        npm install

    # Execução dos Testes
    - name: Execução dos Testes
      run: mocha src/test/convert.js
    
    # Configuração de Usuário e Senha para Login Docker
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      uses: docker/login-action@v3.3.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORLD}}
        
    # Construção da Imagem Docker
    - name: Construção da Imagem Docker
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355
      uses: docker/build-push-action@v6.10.0
      with:
        context: ./DevOps/01_Conversao-Temperatura/src
        file: ./DevOps/01_Conversao-Temperatura/src/Dockerfile
        push: true
        tags: |
          kleberslvaraujo/aula-conv-temp:v1
          kleberslvaraujo/aula-conv-temp:latest
    
    # echo ${{ github.workspace }},
    # ls
    # cat README.md
    # echo `cat README.md`
      
