# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI-Conversão Temperatura

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Possibilita a execução manual via aba Actions
  workflow_dispatch:

jobs:
  # Job name
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DevOps/01_Conversao-Temperatura
        
    # Sequência de Tarefas que serão executadas no job
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup do Node.js
      uses: actions/setup-node@v4.1.0
      with: 
        node-version: 20.10.0

    - name: Instalação do Mocha e dos Pacotes de Teste
      run: |
        echo ${{ github.workspace }},
        ls
      
      #cd ./DevOps\01_Conversao-Temperatura\src,
      # npm install -g mocha
      # npm install
